{% set name = "ws4py" %}
{% set version = "0.6.0" %}
{% set bundle = "tar.gz" %}
{% set hash = "9f87b19b773f0a0744a38f3afa36a803286dd3197f0bb35d9b75293ec7002d19" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python
    - pip

  run:
    - python

test:
  imports:
    - ws4py
    - ws4py.client
    - ws4py.server

about:
  home: https://github.com/Lawouach/WebSocket-for-Python
  license_file: LICENSE
  license: BSD 3-Clause
  license_family: BSD
  summary: 'WebSocket client and server library for Python 2, 3, and PyPy'
  dev_url: https://github.com/Lawouach/WebSocket-for-Python
  doc_url: https://ws4py.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
