travis:
  secure:
    BINSTAR_TOKEN: s59/JYwL0FiVYDeCxT9kXJhQrcGJZmT21YXbuWDJk8tbXB8Bq+dIVb96fSC4eGgaFb5E1aLMGShTZttLh6x08aTPMRP9TWnfI6hidSkxAy6mse762VL9lfJSgewYQd5h3OG5kgPhqzS3cZx6rScDJBS04WFxLfy+/bdHL1+VrGj/k6vH5zFZiPi8MmJG/W/vP9w/weoPq0ymeH6jwxlsrWtKcNRN/2Zv6maS2UWjFyzoZEYMnWAMM3U4xCLXSaCfzG5SQ7rFvVhwmBgWZbV6u+aCUwO+xX6XZfSA1rcDay8WgsNC1tl1mTIYXkB4f2JH666AjtANJ6w7GtV5KkI7SLOo++LehJiKgIyyDOHbtKxVQTiU1opRGksrrfNfo1ttPxVcC/5qGFqueKXu9Y7tOG7sEhqmldxEdDGCpnol+j6UL/byLT7wjq4dJ1B/9G7bKA7Uyx/rx+k2esZFgy3goEmoQ7atpZNoAUWIdN0PKfwDfzWtM54nn8OuXtiY5s5B9iMHDDWGYvJVzaHFuRbWBk4lnrhqLbxjM/V3jnyZGr7jBUhJwQthkLUOBFhIZTDRha5MWthUsOxlNwPD8tnuWCLhjDptt9xwIbpvwMMmxQ7PBPPpzv2u2IgelgS9abaqGOiADyGuO1IlgpWJ/c1FR6FkDkb+VZ4txxknkr5BmHc=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
